// Copy the widget's sources into the generated Android project and declare the
// plugin, so `npx cap sync` picks it up.
//
// android/ is generated by `npx cap add android` in CI and is not tracked in
// git, so widget sources live in native/widget/ and are copied in here — the
// same pattern as android-version.mjs, android-signing.mjs and
// android-manifest.mjs. Must run AFTER `cap sync` and BEFORE the gradle build.
//
// What it does:
//   1. copies .kt sources into the app's java package dir
//   2. copies res/ into the app's res/ (layouts, drawables, values, xml)
//   3. copies the widget's AndroidManifest.xml in, which the Android manifest
//      merger picks up automatically from the app module
//   4. registers CycleWidgetPlugin in MainActivity so the JS bridge exists
import { readFileSync, writeFileSync, existsSync, mkdirSync, cpSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const JAVA_PKG = 'android/app/src/main/java/com/red/tracker/widget';
const RES_DIR = 'android/app/src/main/res';
const SRC = 'native/widget';

if (!existsSync('android')) {
  console.error('no android/ — run `npx cap add android` first');
  process.exit(1);
}

// 1. Kotlin sources.
mkdirSync(JAVA_PKG, { recursive: true });
for (const f of readdirSync(join(SRC))) {
  if (!f.endsWith('.kt')) continue;
  cpSync(join(SRC, f), join(JAVA_PKG, f));
}

// 2. Resources. Merged into the app's res/ rather than replacing it: the app
//    already has its own res/ tree from the Capacitor template, and cpSync with
//    force:true only overwrites colliding names.
for (const sub of readdirSync(join(SRC, 'res'))) {
  const from = join(SRC, 'res', sub);
  const to = join(RES_DIR, sub);
  mkdirSync(to, { recursive: true });
  cpSync(from, to, { recursive: true, force: true });
}

// 3. Declare the widget receiver in the app's main manifest.
//
// NOT a file copy: android/app/src/main/AndroidManifest.xml is the Capacitor
// template's manifest and already holds the activity, the file provider and the
// launcher intent. Overwriting it would delete all of that and the app would
// not build. The receiver element is inserted before </application> instead,
// idempotently.
const MANIFEST = 'android/app/src/main/AndroidManifest.xml';
if (!existsSync(MANIFEST)) {
  console.error(`no ${MANIFEST} — run \`npx cap add android\` first`);
  process.exit(1);
}
{
  let s = readFileSync(MANIFEST, 'utf8');
  if (!s.includes('CycleWidgetProvider')) {
    const RECEIVER = [
      '        <receiver',
      '            android:name="com.red.tracker.widget.CycleWidgetProvider"',
      '            android:exported="false">',
      '            <intent-filter>',
      '                <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />',
      '            </intent-filter>',
      '            <meta-data',
      '                android:name="android.appwidget.provider"',
      '                android:resource="@xml/widget_cycle_info" />',
      '        </receiver>',
    ].join('\n');
    // Anchor on the closing </application> tag, which the Capacitor template
    // always has. Inserting before it keeps the file well formed.
    const idx = s.lastIndexOf('</application>');
    if (idx === -1) {
      console.error(`${MANIFEST} has no </application> — refusing to patch`);
      process.exit(1);
    }
    s = s.slice(0, idx) + RECEIVER + '\n    ' + s.slice(idx);
    writeFileSync(MANIFEST, s);
    console.log('declared CycleWidgetProvider in the app manifest');
  }
}

// 4. Register the plugin. Capacitor 7 discovers plugins listed in MainActivity;
//    without this the JS call is a silent no-op. The generated template is bare
//    (an empty class body), so when there is no onCreate to hook into we add
//    one — the documented Capacitor pattern is registering before super.onCreate.
const MAIN = 'android/app/src/main/java/com/red/tracker/MainActivity.java';
if (!existsSync(MAIN)) {
  console.error(`no ${MAIN} — cannot register the widget plugin`);
  process.exit(1);
}
{
  let s = readFileSync(MAIN, 'utf8');
  if (!s.includes('CycleWidgetPlugin')) {
    // Import after the existing Capacitor import, which the template has.
    const anchor = /import com\.getcapacitor\.BridgeActivity;?/;
    if (!anchor.test(s)) {
      console.error(`${MAIN} has no BridgeActivity import — refusing to guess an insertion point`);
      process.exit(1);
    }
    s = s.replace(anchor, (m) => `${m}\nimport android.os.Bundle;\nimport com.red.tracker.widget.CycleWidgetPlugin;`);
    if (/protected void onCreate\(/.test(s) && s.includes('super.onCreate(savedInstanceState);')) {
      // A project-defined onCreate exists: register inside it, first.
      s = s.replace(/(\s*)super\.onCreate\(savedInstanceState\);/, '$1registerPlugin(CycleWidgetPlugin.class);$1super.onCreate(savedInstanceState);');
    } else {
      // Stock template: add an onCreate that registers the plugin.
      // The \s* covers both empty-body shapes.
      s = s.replace(/public class MainActivity extends BridgeActivity \{\s*\}/, `public class MainActivity extends BridgeActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        registerPlugin(CycleWidgetPlugin.class);
        super.onCreate(savedInstanceState);
    }
}`);
    }
    if (!s.includes('registerPlugin(CycleWidgetPlugin.class)')) {
      console.error(`${MAIN} — could not anchor plugin registration`);
      process.exit(1);
    }
    writeFileSync(MAIN, s);
    console.log('registered CycleWidgetPlugin in MainActivity.java');
  }
}

console.log('widget sources copied into android/');
