// Adds a release signing config to android/app/build.gradle, using the keystore
// supplied through environment variables.
//
// Why: without this, `assembleDebug` signs with the debug keystore that the
// Android Gradle plugin generates fresh on every CI runner. Same package name,
// different signing key each build, so Android rejects the update with
// INSTALL_FAILED_UPDATE_INCOMPATIBLE ("App not installed" / "conflict").
//
// Required env:
//   KEYSTORE_FILE      path to the .jks
//   KEYSTORE_PASSWORD  keystore password
//   KEY_ALIAS          key alias
//   KEY_PASSWORD       key password
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const file = 'android/app/build.gradle';
if (!existsSync(file)) {
  console.error(`no ${file} — run \`npx cap add android\` first`);
  process.exit(1);
}

for (const k of ['KEYSTORE_FILE', 'KEYSTORE_PASSWORD', 'KEY_ALIAS', 'KEY_PASSWORD']) {
  if (!process.env[k]) {
    console.error(`missing env ${k}; refusing to build an unsigned release`);
    process.exit(1);
  }
}

// The release signing config is injected here rather than committed, because
// android/ is generated by `cap add android` and is not tracked in git.

// Returns the index just past the `}` that closes the block whose opening brace
// is at `open`. Naive brace counting is correct here: the template has no braces
// inside strings or comments.
function endOfBlock(src, open) {
  let depth = 0;
  for (let i = open; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') {
      depth--;
      if (depth === 0) return i + 1;
    }
  }
  return -1;
}

// Finds `name {` at the start of a line (ignoring indentation) and returns the
// range of the whole block, or null.
function findBlock(src, name) {
  const re = new RegExp(`(^|\\n)([ \\t]*)${name}\\s*\\{`, 'm');
  const m = re.exec(src);
  if (!m) return null;
  const open = src.indexOf('{', m.index);
  const end = endOfBlock(src, open);
  if (end < 0) return null;
  return { indent: m[2], start: m.index + m[1].length, open, end };
}

let s = readFileSync(file, 'utf8');

if (s.includes('signingConfigs {')) {
  console.log('build.gradle already has a signingConfigs block, leaving it alone');
  process.exit(0);
}

// signingConfigs is a direct child of android { }, so it goes after the
// defaultConfig { } block closes — inserting inside defaultConfig is invalid DSL
// and Gradle fails with "could not find method signingConfigs()".
const defaultConfig = findBlock(s, 'defaultConfig');
if (!defaultConfig) {
  console.error('could not find a defaultConfig { } block in ' + file);
  process.exit(1);
}
const block = `\n\n${defaultConfig.indent}signingConfigs {\n${defaultConfig.indent}    release {\n${defaultConfig.indent}        storeFile file(System.getenv("KEYSTORE_FILE"))\n${defaultConfig.indent}        storePassword System.getenv("KEYSTORE_PASSWORD")\n${defaultConfig.indent}        keyAlias System.getenv("KEY_ALIAS")\n${defaultConfig.indent}        keyPassword System.getenv("KEY_PASSWORD")\n${defaultConfig.indent}    }\n${defaultConfig.indent}}`;
s = s.slice(0, defaultConfig.end) + block + s.slice(defaultConfig.end);

// Point the release build type at it. minify stays off: no ProGuard rules ship.
const buildTypes = findBlock(s, 'buildTypes');
if (!buildTypes) {
  console.error('could not find a buildTypes { } block in ' + file);
  process.exit(1);
}
const release = findBlock(s.slice(buildTypes.open, buildTypes.end), 'release');
if (!release) {
  console.error('could not find a release { } block inside buildTypes');
  process.exit(1);
}
const releaseAbsOpen = buildTypes.open + release.open;
s = s.slice(0, releaseAbsOpen + 1) + `\n${release.indent}    signingConfig signingConfigs.release` + s.slice(releaseAbsOpen + 1);

writeFileSync(file, s);
console.log('added release signingConfig to ' + file);
